### ISSUE TITLE
Are errStrings defined?

### ISSUE THREAD

**Issue by piersy** [getyoti/yoti-go-sdk#73]
> ```go
> activityDetails, errStrings := client.GetActivityDetails(yotiOneTimeUseToken)
> if len(errStrings) != 0 {
>   // handle unhappy path
> }
> ```

The example above, given in the readme implies that errStrings can be handled, but there is no documentation listing what error strings can be returned.

Without knowing what errStrings can be returned callers of `GetActivityDetails` will be unable to write any code to handle the unhappy path aside from just failing. This prevents them from giving any feedback to callers that they in turn could react to. Notably they will be unable to determine if the error returned was as a consequence of bad input or if it was caused by a temporary server failure and are able to retry.

**Comment by echarrod** [comment]
Thanks for raising this @piersy. This is something we are going to change in the major (v3.0.0), which will be released at the start of next year. 

We will either return 1) a list of errors, or 2) a single error which could potentially have wrapped errors inside of it. 

As part of this, we will ensure there is a way of checking whether the error is the result of bad input, or something else, which allows the caller to have flexibility on what they want to do with the result.

**Comment by piersy** [comment]
@echarrod Thanks for the update :+1:

**Comment by echarrod** [comment]
This was released in [v3.0.0](https://github.com/getyoti/yoti-go-sdk/releases/tag/v3.0.0), and the errors that can be thrown from ActivityDetails are listed in https://github.com/getyoti/yoti-go-sdk/blob/v3.0.0/yotierror/activitydetails.go 👍
